<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\0-DTOs\SSF.PortalBI.DTOs.csproj" />
    <ProjectReference Include="..\2-BusinessClass\SSF.PortalBI.BusinessClass.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
